"""
Django settings for industrial_site project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env dosyasından ortam değişkenlerini yükle (python-dotenv kuruluysa; proje kökünde .env)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass  # python-dotenv yoksa env değişkenleri sistem/ortamdan okunur


# Quick-start development settings - production'da env ile override edin
# https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY: Production'da mutlaka ortam değişkeninden gelmeli (güçlü, rastgele)
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-)62@c!n$@k=&v-bh+@p+0b85v_t(686@y_s^q+8!#7^62&#mkg")

# DEBUG: Production'da False. .env'de DEBUG=False veya boş bırakıp ALLOWED_HOSTS ile kullanın
_debug = os.getenv("DEBUG", "true").strip().lower()
DEBUG = _debug in ("1", "true", "yes", "on")

# ALLOWED_HOSTS: Virgülle ayrılmış (örn. .env: ALLOWED_HOSTS=example.com,www.example.com)
_allowed = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]

# CSRF_TRUSTED_ORIGINS: HTTPS domain'leriniz (örn. https://example.com,https://www.example.com)
_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "http://127.0.0.1:8000").strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'public',
    'dealer',
    'warehouse',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'industrial_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings',
                'dashboard.context_processors.dashboard_nav',
                'dealer.context_processors.dealer_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'industrial_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Production: python manage.py collectstatic ile STATIC_ROOT'a toplanır; web sunucusu (Nginx) oradan servis eder.

STATIC_URL = os.getenv("STATIC_URL", "/static/").rstrip("/") + "/"
STATIC_ROOT = os.getenv("STATIC_ROOT", str(BASE_DIR / "staticfiles")).strip() or str(BASE_DIR / "staticfiles")
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = os.getenv("MEDIA_URL", "/media/").rstrip("/") + "/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", str(BASE_DIR / "media")).strip() or str(BASE_DIR / "media")

# PayTR online ödeme (bayi). Anahtarlar boşsa mock mod; doluysa gerçek PayTR token/iframe akışı.
# .env veya ortam değişkeni: PAYTR_MERCHANT_ID, PAYTR_MERCHANT_KEY, PAYTR_MERCHANT_SALT, PAYTR_TEST_MODE
PAYTR_MERCHANT_ID = os.getenv("PAYTR_MERCHANT_ID", "").strip()
PAYTR_MERCHANT_KEY = os.getenv("PAYTR_MERCHANT_KEY", "").strip()
PAYTR_MERCHANT_SALT = os.getenv("PAYTR_MERCHANT_SALT", "").strip()
_paytr_test = os.getenv("PAYTR_TEST_MODE", "true").strip().lower()
PAYTR_TEST_MODE = _paytr_test in ("1", "true", "yes", "on")

LOGIN_REDIRECT_URL = 'dealer:dashboard'
LOGOUT_REDIRECT_URL = 'home'
