# Generated by Django 6.0.2 on 2026-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LOVE Otomotive', max_length=200, verbose_name='Site / Firma adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('phone', models.CharField(blank=True, default='+90 212 000 00 00', max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, default='info@example.com', max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('iban', models.CharField(blank=True, default='TR00 0000 0000 0000 0000 0000 00', max_length=100, verbose_name='Havale/EFT IBAN')),
                ('primary_color', models.CharField(default='#1e3a5f', max_length=7, verbose_name='Ana renk (hex)')),
                ('secondary_color', models.CharField(default='#0f2942', max_length=7, verbose_name='İkincil renk (hex)')),
                ('accent_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Vurgu rengi (hex)')),
            ],
            options={
                'verbose_name': 'Site ayarları',
                'verbose_name_plural': 'Site ayarları',
            },
        ),
    ]
