# Generated by Django 6.0.2 on 2026-02-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_stock_and_dealer_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('shipped', 'Kargoda'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal')], default='pending', max_length=20),
        ),
    ]
