# Generated by Django 6.0.2 on 2026-02-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0009_product_stock_on_hand_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_on_hand',
            field=models.PositiveIntegerField(default=0, verbose_name='Gerçek stok'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_reserved',
            field=models.PositiveIntegerField(default=0, verbose_name='Rezerve'),
        ),
    ]
