# Generated by Django 6.0.2 on 2026-02-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_alter_product_stock_on_hand_and_more'),
        ('dealer', '0010_dealerprofile_professional_fields'),
    ]

    operations = [
    ]
