# Generated by Django 6.0.2 on 2026-02-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0011_merge_20260226_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Firma adı'),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Giriş onaylı'),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
    ]
