# Generated by Django 6.0.2 on 2026-02-26 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0016_dealerpayment_description_created_by_created_at_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealerpayment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Bayi ödemesi', 'verbose_name_plural': 'Bayi ödemeleri'},
        ),
        migrations.AlterField(
            model_name='dealerpayment',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='dealerpayment',
            name='payment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Ödeme tarihi'),
        ),
    ]
