# Generated by Django 6.0.2 on 2026-02-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0017_alter_dealerpayment_options_alter_dealerpayment_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('online', 'Online (website)'), ('manual', 'Manual (admin panel)')], default='online', max_length=20, verbose_name='Sipariş kaynağı'),
        ),
    ]
