# Generated by Django 6.0.2 on 2026-02-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0019_order_total_amount_and_orderitem_line_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim fiyat (TL)'),
        ),
    ]
