# Generated by Django 6.0.2 on 2026-02-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0020_alter_orderitem_unit_price'),
        ('dealer', '0021_orderitem_manual_price_override'),
    ]

    operations = [
    ]
