# Generated by Django 6.0.2 on 2026-02-27 14:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0023_ledger_account_transaction_payment_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Varsayılan: ürün fiyatı. 'Fiyatı elle gir' işaretlenirse bu alan düzenlenebilir.", max_digits=10, verbose_name='Birim fiyat (TL)'),
        ),
    ]
