# Generated by Django 6.0.2 on 2026-03-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0025_mail_order_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='source',
            field=models.CharField(choices=[('ORDER_SHIPPED', 'Sipariş kargoya çıktı'), ('PAYMENT', 'Ödeme'), ('MANUAL_ADJ', 'Manuel düzeltme'), ('MAIL_ORDER', 'Mail Order')], max_length=20, verbose_name='Kaynak'),
        ),
    ]
