# Generated by Django 6.0.2 on 2026-03-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0026_alter_accounttransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerpayment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Havale / EFT'), ('mail_order', 'Mail Order'), ('online_payment', 'Online Ödeme')], default='bank_transfer', max_length=20, verbose_name='Ödeme yöntemi'),
        ),
        migrations.AddField(
            model_name='dealerpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal')], default='confirmed', max_length=20, verbose_name='Durum'),
        ),
    ]
