# Generated by Django 6.0.2 on 2026-03-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0027_dealerpayment_payment_method_dealerpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='source',
            field=models.CharField(choices=[('ORDER_SHIPPED', 'Sipariş kargoya çıktı'), ('PAYMENT', 'Ödeme (Legacy)'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE_PAYMENT', 'Online Payment'), ('MANUAL_ADJ', 'Manuel düzeltme'), ('MAIL_ORDER', 'Mail Order')], max_length=20, verbose_name='Kaynak'),
        ),
    ]
