# Generated by Django 6.0.2 on 2026-03-06 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0028_alter_accounttransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='dealer.dealerpayment', verbose_name='Ödeme kaydı'),
        ),
    ]
