# Generated by Django 6.0.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0029_paymentallocation_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransferNotice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Tutar (₺)")),
                ("transfer_date", models.DateField(verbose_name="Havale tarihi")),
                ("note", models.TextField(blank=True, verbose_name="Not")),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="bank_transfer_receipts/%Y/%m/", verbose_name="Dekont"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bank_transfer_notices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transfer_notices",
                        to="dealer.dealerprofile",
                    ),
                ),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transfer_notices",
                        to="dealer.dealerpayment",
                        verbose_name="Oluşan ödeme kaydı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Havale / EFT bildirimi",
                "verbose_name_plural": "Havale / EFT bildirimleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
